ProjekatSkije/ProjekatIznajmljivanjeSkija/ProjekatIznajmljivanjeSkija/Controllers/IznajmljivanjeController.cs
using ProjekatIznajmljivanjeSkija.Models;
using ProjekatIznajmljivanjeSkija.Models.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjekatIznajmljivanjeSkija.Controllers
{
    public class IznajmljivanjeController : Controller
    {
        // GET: Iznajmljivanje
        Database bazaPodataka;

        public IznajmljivanjeController()
        {
            bazaPodataka = new Database();
        }
        public ActionResult Index()
        {
            List<Proizvod> skije = bazaPodataka.getAllSkije();
            List<Proizvod> oprema = bazaPodataka.getAllOprema();
            ViewBag.skije = skije;
            ViewBag.oprema = oprema;
            return View();
        }
        [HttpPost]
        public ActionResult Iznajmi()
        {
            bool izabrano = true;
            int IDskije = int.Parse(Request.Form["skije"]);
            int IDoprema = int.Parse(Request.Form["oprema"]);
            if (IDskije == 0 && IDoprema == 0)
            {
                TempData["greskaStanje"] = "Morate izabrati bar jedan proizvod";
                izabrano = false;

            }
            else
            {
                bazaPodataka.stampajRacun(IDskije, IDoprema);
            }

            if(Database.greskaStranje!="")
            {
                TempData["greskaStanje"] = Database.greskaStranje;
            }

          else 
            {
                if (izabrano)
                {
                    TempData["uspeh"] = "Uspesno ste iznajmili svoje proizvode!";
                }
            }

            
            return RedirectToAction("Index");
        }
    }
}

ProjekatSkije/ProjekatIznajmljivanjeSkija/ProjekatIznajmljivanjeSkija/Controllers/RacunController.cs
using Microsoft.Ajax.Utilities;
using ProjekatIznajmljivanjeSkija.Models;
using ProjekatIznajmljivanjeSkija.Models.entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjekatIznajmljivanjeSkija.Controllers
{
    public class RacunController : Controller
    {
        // GET: Racun
        Database bazaPodataka;

        public RacunController()
        {
            bazaPodataka = new Database();
        }
        public ActionResult Index(Racun racun)
        {            
            if(racun.ID==0)
            {
                ViewBag.racun = "";
            }
            else
            {
                ViewBag.racun = "nije prazno";
            }
            return View();
        }

        public ActionResult RacunPartial(Racun racun)
        {
            return PartialView("RacunPartial", racun);
        }

        [HttpPost]
        public ActionResult PretraziRacun()
        {
            string id = Request["txtsearch"];
            int ID;
            string button = Request["button"];
        if(button=="search")
            {
                if (int.TryParse(id, out ID))
                {
                    Racun racun = bazaPodataka.traziRacun(ID);
                    if (racun.ID == 0)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return RedirectToAction("Index", racun);
                    }
                }
                else
                {
                    TempData["UnosBroj"] = "U polju se mora upisati broj!";
                    return RedirectToAction("Index");

                }
            }
        else
            {
                return RedirectToAction("Index");
            }




        }

        [HttpPost]
        public ActionResult Storniranje()
        {
            int id = int.Parse(Request["id"]);
            bazaPodataka.StornirajRacun(id);
            TempData["storniranje"] = "Uspesno ste stornirali racun sa sifrom: " + id;
            return RedirectToAction("Index");
        }
    }
}

ProjekatSkije/ProjekatIznajmljivanjeSkija/ProjekatIznajmljivanjeSkija/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container" style="padding-left:0px; padding-right:0px;" >
        <div class="page-header" style="background-color:white;">
            <h1> Izdavanje skija i opreme za skije</h1>
            <a href="index.html" style="height:auto; margin:auto"><img id="logo" src="/images/skije3.jpg" alt="Photo" style="width:100%;"></a><strong>

            </strong>
        </div>
        <div class="navbar-collapse collapse" style="padding-left:0px; padding-right:0px;">

            <nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="padding-left:0px; padding-right:0px;">
                <a class="navbar-brand" href="@Url.Action("Index", "Iznajmljivanje")">Iznajmljivanje</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                       
                        <a class="nav-item nav-link active" href="@Url.Action("Index", "Racun")">Pretraga racuna <span class="sr-only">(current)</span></a>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="container body-content" style="background-color:azure">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>